### ISSUE TITLE
dotnet 5 support info

### ISSUE THREAD

**Issue by ChaosEngine** [redhat-developer/kestrel-linux-transport#101]
Is this kestrel transport supported for dotnet 5 based aspnet core
If not, could you please state this somewhere in the docs?

**Comment by ChaosEngine** [comment]
I investigated possible run on dotnet 5 and observed error on nginx reverse proxy (and not on dotnet-3.1 or on apache) when enabled your transport package. When disabled kestrel-linux-transport was disabled - error went away.

**Comment by xXBuilderBXx** [comment]
Same here using this with nginx proxy it seems to fail half the time with a 502 bad gateway error messages.
