### ISSUE TITLE
netstandard library problem

### ISSUE THREAD

**Issue by igorvlassov** [redhat-developer/kestrel-linux-transport#64]
Dear Sirs,

I have following problem: 
In our app we have WebHost in separated netstandard2.0 library by design. Could you please add netstandard2.0 as additional TargetFramework please?

**Comment by tmds** [comment]
I have added netstandard2.0 as a target framework: https://github.com/redhat-developer/kestrel-linux-transport/commit/4a12476263a2bc6a8317b7c646dad0457398348e
You can build a package from the release/2.1 branch:
```
git clone https://github.com/redhat-developer/kestrel-linux-transport.git
cd kestrel-linux-transport
git checkout release/2.1
cd src/RedHat.AspNetCore.Server.Kestrel.Transport.Linux
dotnet pack -c Release
```

**Comment by igorvlassov** [comment]
Thanks a lot!
