### ISSUE TITLE
Bedrock refactoring

### ISSUE THREAD

**Issue by tmds** [redhat-developer/kestrel-linux-transport#83]
With https://github.com/redhat-developer/kestrel-linux-transport/pull/80 the initial implementation of [bedrock abstractions](https://github.com/aspnet/AspNetCore/issues/10308) is:
```cs
public class LinuxTransportFactory : IConnectionListenerFactory
{
    LinuxTransport(IOptions<LinuxTransportOptions> options);
}
internal Transport : IConnectionListener {}

DI injection:
services.AddSingleton<IConnectionListenerFactory, LinuxTransportFactory>();
```

This comes from the previous abstraction, which only allowed a transport to handle in-coming connections.

We should add support for out-coing connections (`IConnectionFactory`) and allow re-using the `TransportThread`s between `IConnectionFactory` and `IConnectionListenerFactory`.

This would look like:
```cs
public class LinuxTransport: IConnectionListenerFactory, IConnectionFactory, IAsyncDisposable
{
    LinuxTransport(IOptions<LinuxTransportOptions> options);
    DisposeAsync(); // controls life-time of memorypool, transport threads, ...
}
internal ConnectionFactory : IConnectionFactory
{
public ConnectionFactory(LinuxTransport transport) {}
ConnectAsync(...) => _transport.ConnectAsync(...);
}
internal ConnectionListenerFactory : IConnectionListenerFactory
{
public ConnectionListenerFactory(LinuxTransport transport) {}
BindAsync(...) => _transport.BindAsync(...);
}

DI injection:
services.AddSingleton<LinuxTransport>();
services.AddSingleton<IConnectionFactory, ConnectionFactory>();
services.AddSingleton<IConnectionListenerFactory, ConnectionListenerFactory>();
```

@halter73 @davidfowl fyi

**Comment by davidfowl** [comment]
I'm working on a way to decouple this assembly from Kestrel, track this https://github.com/aspnet/AspNetCore/issues/11479

**Comment by davidfowl** [comment]
This is done right?

**Comment by tmds** [comment]
Not yet, out-bound connections are not supported.

**Comment by tkp1n** [comment]
FYI: An example on how this could be achieved can be found in [tkp1n/IoUring](https://github.com/tkp1n/IoUring):

* Transport threads are re-used across multiple in- and outbound-connections.
* Client connections are assigned a transport thread using round robin. 
* Registration of the Transport layer is done via an `IServiceCollection` extension method.

**Comment by tmds** [comment]
@tkp1n do you want to make a PR? :smile:
