### ISSUE TITLE
Dotnet core 3.0 custom packages are setup differently

### ISSUE THREAD

**Issue by jmrnilsson** [redhat-developer/kestrel-linux-transport#97]
Could find where to put Nuget.Config and no such place seems left for dotnet core 3.0. So custom packages add added with 

>  dotnet add package RedHat.AspNetCore.Server.Kestrel.Transport.Linux -s https://www.myget.org/F/redhat-dotnet/api/v3/index.json

None of them support 3.0 yet.. -Has the changes merged into the regular Socket-variant. It's a lot faster now anyways. 

info : Restoring packages for .......
info :   GET https://api.nuget.org/v3-flatcontainer/redhat.aspnetcore.server.kestrel.transport.linux/index.json
info :   GET https://www.myget.org/F/redhat-dotnet/api/v3/flatcontainer/redhat.aspnetcore.server.kestrel.transport.linux/index.json
info :   OK https://www.myget.org/F/redhat-dotnet/api/v3/flatcontainer/redhat.aspnetcore.server.kestrel.transport.linux/index.json 57ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/redhat.aspnetcore.server.kestrel.transport.linux/index.json 489ms
error: Unable to find a stable package RedHat.AspNetCore.Server.Kestrel.Transport.Linux with version
error:   - Found 456 version(s) in https://www.myget.org/F/redhat-dotnet/api/v3/index.json [ Nearest version: 3.0.0-191007-1144 ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error:   - Found 0 version(s) in nuget.org
error: Package 'RedHat.AspNetCore.Server.Kestrel.Transport.Linux' is incompatible with 'all' frameworks in project

**Comment by blackie1019** [comment]
I got the same issue from add package into project with blow logs:
➜  RexBet.BetEngine.Application git:(upstream-master) ✗ dotnet add package RedHat.AspNetCore.Server.Kestrel.Transport.Linux -s https://www.myget.org/F/redhat-dotnet/api/v3/index.json
  Writing /var/folders/z3/3dtbzfj158j25nq2f39dg4bjwcdq9g/T/tmpo3Bsm3.tmp
info : Adding PackageReference for package 'RedHat.AspNetCore.Server.Kestrel.Transport.Linux' into project '/Users/ct.tsai/Desktop/Repo/skyline/deliverables/application-betengine/src/RexBet.BetEngine.Application/RexBet.BetEngine.Application.csproj'.
info : Restoring packages for /Users/ct.tsai/Desktop/Repo/skyline/deliverables/application-betengine/src/RexBet.BetEngine.Application/RexBet.BetEngine.Application.csproj...
info :   CACHE http://team.sb.skylinetw.com:8081/repository/nuget-group/FindPackagesById()?id='RedHat.AspNetCore.Server.Kestrel.Transport.Linux'&semVerLevel=2.0.0
info :   GET https://api.nuget.org/v3-flatcontainer/redhat.aspnetcore.server.kestrel.transport.linux/index.json
info :   CACHE https://www.myget.org/F/redhat-dotnet/api/v3/flatcontainer/redhat.aspnetcore.server.kestrel.transport.linux/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/redhat.aspnetcore.server.kestrel.transport.linux/index.json 880ms
error: Unable to find a stable package RedHat.AspNetCore.Server.Kestrel.Transport.Linux with version 
error:   - Found 494 version(s) in rh [ Nearest version: 3.0.0-191007-1144 ]
error:   - Found 0 version(s) in Team Nuget
error:   - Found 0 version(s) in nuget.org
error: Package 'RedHat.AspNetCore.Server.Kestrel.Transport.Linux' is incompatible with 'all' frameworks in project '/Users/ct.tsai/Desktop/Repo/skyline/deliverables/application-betengine/src/RexBet.BetEngine.Application/RexBet.BetEngine.Application.csproj'.

**Comment by tmds** [comment]
> error: - Found 456 version(s) in https://www.myget.org/F/redhat-dotnet/api/v3/index.json [ Nearest version: 3.0.0-191007-1144 ]

You should add a --Version argument to `dotnet add package` so it picks one of these.
for example:
```
$ dotnet add package RedHat.AspNetCore.Server.Kestrel.Transport.Linux -s https://www.myget.org/F/redhat-dotnet/api/v3/index.json --version '3.0.0-*'
```
